kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: granulate-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: granulate-cluster-role
subjects:
  - kind: ServiceAccount
    name: granulate-service-account
    namespace: {{ .Values.namespace }}
