apiVersion: apps/v1
kind: Deployment
metadata:
  name: granulate-maestro
  namespace: {{ .Values.namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: granulate-maestro
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: granulate-maestro
    spec:
      containers:
      - env:
        - name: MAESTRO_CLIENT_ID
          value: {{ .Values.b64ClientId }}
        - name: MAESTRO_SERVICE_NAME
          value: {{ .Values.clusterName }}
        - name: MAESTRO_RUN_ON_K8S
          value: 'TRUE'
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MAESTRO_SERVER_HOST
          value: https://containerunits.granulate.io
        image: index.docker.io/granulate/maestro:latest
        imagePullPolicy: IfNotPresent
        name: granulate-maestro
        resources:
          limits:
            cpu: "2"
            memory: 2560Mi
          requests:
            cpu: "1"
            memory: 1536Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: granulate-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: granulate-service-account
      serviceAccountName: granulate-service-account
      terminationGracePeriodSeconds: 3
